spring.application.name=tokenizacao

server.port=8080

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/foursys_banco_tokenizacao?createDatabaseIfNotExist=true&serverTimezone=America/Sao_Paulo}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.servlet.session.timeout=15m
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.same-site=lax
# Em producao (HTTPS), habilitar:
# server.servlet.session.cookie.secure=true
